export const CART_ITEMS = "CART_ITEMS";
export const CATEGORIES = "CATEGORIES";
export const BANNER_LIST = "BANNER_LIST";
export const GET_SEARCHED_PRODUCTS = "GET_SEARCHED_PRODUCTS";
export const GET_SEARCH_PARAMS = "GET_SEARCH_PARAMS";